### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by martin2350** [carway/springboot-baiduOcr-structurization#1]
你好！

看到项目的result目录里result1.png图片可以对图片进行解析，但是这个结果是怎么运行起来呢？项目里没有相关的表单，还请指导！谢谢！

**Comment by carway** [comment]
src/main/resources/source目录下有1.jpg图片，result目录下的图片结果就是这个得来的。启动springboot项目，用postman调用http://localhost:80/api/ocr/handle接口上传图片就行了。

**Comment by martin2350** [comment]
好的，非常感谢！
